Head:
  DocId: "tb_real_dia_cupom1"
  Version: "v1"
  StartTime: "2023-01-01 00:00:00"
  Schedule: "0 9 * * *"
  Retries: "Low"
  RetryDelay: "Short"
  Gerencia: "Front"
  Coord: "RGM"
  ValueStream: "Franqueado"
  Tags: "factory"

Table:
  ProjectId: "trusted-zone"
  DatasetId: "sellout"
  TableId: "tb_real_dia_cupom"

Task:
  Operator: "BigQueryInsertJobOperator"
  Query: "CALL prc_load_tb_real_dia_cupom"
  # Configuration:
  #   Query:
  #     Query: "CALL prc_load_tb_real_dia_cupom"
  #     UseLegacySql: False

DataQuality:
  Operator: "DummyOperator"

Dependencies:
  - TableId: tb_loja_venda_so
    PokeInterval: "Short"
    DependencyMode: 'last_today'
