name: Generate DAG from YAML

on:
  push:
    branches:
      - main
    paths:
      - '**/dag_factory/config/*.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**/dag_factory/config/*.yaml'

jobs:
  generate_dag:
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GH_PAT  }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up SSH
        run: |
          set -e
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts


      - name: Run DAG generator
        run: |
          set -e
          python dag_factory/main.py --output dags/generated/

      - name: Commit and push DAG files
        run: |
          set -e
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
          git add dags/generated/*.py
          git commit -m "Generated DAG files from YAML" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT  }}@github.com/${{ github.repository }}
          git push || echo "No changes to push"
