name: GB DAG FACTORY
on:
  push:
    branches:
      - main
    paths:
      - '**/dag_factory/config/*.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**/dag_factory/config/*.yaml'
      
jobs:
  GB_DAG_FACTORY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          #token: ${{ secrets.GH_PAT  }}

      - name: Configurando o ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Instalando dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar o gerador de DAG
        run: |
          set -e
          python dag_factory/main.py --output dags/generated/

      - name: Commit e push do arquivo dag.py
        run: |
          set -e
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
          git add dags/generated/*.py
          git commit -m "DAG gerada com sucesso!!!" || echo "No changes to commit"
          git push || echo "No changes to push"
      
      - name: Inicializar o Airflow Database
        run: |
          airflow db init

      - name: Validando a DAG
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/dags
          find ./dags/generated -name "*.py" -exec python {} \; > /dev/null
          if [ $? -ne 0 ]; then exit 1; fi


        
