name: Generate DAG from YAML

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/dag_factory/config/*.yaml'

jobs:
  generate_dag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DAG generator
        run: |
          for config_file in dag_factory/config/*.yaml; do
            python dag_factory/main.py --input "$config_file" --output dags/generated/
          done

      - name: Commit and push DAG files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
          git add dags/generated/*.py
          git commit -m "Generated DAG files from YAML" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ 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 }}@github.com/${{ github.repository }}
          git push || echo "No changes to push"
