name: Testes Unitários

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Airflow vTest 
    strategy:
      matrix:
        airflow-version: ['2.1.0', '2.2.0', '2.3.0', '2.4.0', '2.5.0']

    continue-on-error: true

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Instalar dependências
        run: |
          pip install pytest
          pip install SQLAlchemy
          pip install apache-airflow==${{ matrix.airflow-version }}

      - name: Inicializar SQLite
        run: |
          echo "" > airflow.db
          export AIRFLOW__CORE__SQL_ALCHEMY_CONN="sqlite:///$(pwd)/airflow.db"

      - name: Executar migrações do Airflow
        run: airflow db init

      - name: Executar testes unitários
        run: pytest tests/sensor/test_gb_external_task_sensor.py::TestGbExternalTaskSensor::test_gb_external_task_sensor_last_valid -s
